#include "enderalsegameplugins.h"

#include <ipluginlist.h>
#include <log.h>
#include <transactionalwritefile.h>

#include <QStringEncoder>

using namespace MOBase;

void EnderalSEGamePlugins::writePluginList(const MOBase::IPluginList* pluginList,
                                           const QString& filePath)
{
  QStringEncoder encoder(QStringConverter::Encoding::System);

  QByteArray contents =
      encoder.encode("# This file was automatically generated by Mod Organizer.\r\n");

  bool invalidFileNames = false;

  QStringList plugins = pluginList->pluginNames();
  std::sort(plugins.begin(), plugins.end(),
            [pluginList](const QString& lhs, const QString& rhs) {
              return pluginList->priority(lhs) < pluginList->priority(rhs);
            });

  QStringList PrimaryPlugins = organizer()->managedGame()->primaryPlugins();
  QStringList DLCPlugins     = organizer()->managedGame()->DLCPlugins();
  QSet<QString> ManagedMods =
      QSet<QString>(PrimaryPlugins.begin(), PrimaryPlugins.end());
  QSet<QString> DLCSet = QSet<QString>(DLCPlugins.begin(), DLCPlugins.end());
  ManagedMods.subtract(DLCSet);
  PrimaryPlugins.append(QList<QString>(ManagedMods.begin(), ManagedMods.end()));

  // we need to force some plugins because those are not force-loaded
  // by the game but are considered primary plugins for users
  contents.append("*Enderal - Forgotten Stories.esm\r\n");
  contents.append("*SkyUI_SE.esp\r\n");

  // TODO: do not write plugins in OFFICIAL_FILES container
  for (const QString& pluginName : plugins) {
    if (!PrimaryPlugins.contains(pluginName, Qt::CaseInsensitive)) {
      if (pluginList->state(pluginName) == IPluginList::STATE_ACTIVE) {
        auto result = encoder.encode(pluginName);
        if (encoder.hasError()) {
          invalidFileNames = true;
          qCritical("invalid plugin name %s", qUtf8Printable(pluginName));
        } else {
          contents.append("*");
          contents.append(result);
        }
        contents.append("\r\n");
      } else {
        auto result = encoder.encode(pluginName);
        if (encoder.hasError()) {
          invalidFileNames = true;
          qCritical("invalid plugin name %s", qUtf8Printable(pluginName));
        } else {
          contents.append(result);
        }
        contents.append("\r\n");
      }
    }
  }

  if (invalidFileNames) {
    recordInvalidFileNames();
  }

  TransactionalWriteFile file(filePath);
  if (!file.replaceWith(contents)) {
    recordWriteFailure(filePath, file.errorString());
    return;
  }
}
