#include "starfieldgameplugins.h"

#include <ipluginlist.h>
#include <transactionalwritefile.h>

using namespace MOBase;

StarfieldGamePlugins::StarfieldGamePlugins(MOBase::IOrganizer* organizer)
    : CreationGamePlugins(organizer)
{}

bool StarfieldGamePlugins::mediumPluginsAreSupported()
{
  return true;
}

bool StarfieldGamePlugins::blueprintPluginsAreSupported()
{
  return true;
}

void StarfieldGamePlugins::writePluginList(const IPluginList* pluginList,
                                           const QString& filePath)
{
  if (m_Organizer->managedGame()->loadOrderMechanism() !=
      MOBase::IPluginGame::LoadOrderMechanism::PluginsTxt) {
    return;
  }

  QStringEncoder encoder(QStringConverter::Encoding::System);

  QByteArray contents = encoder.encode(
      "# This file was automatically generated by Mod Organizer.\r\n");

  bool invalidFileNames = false;

  QStringList plugins = pluginList->pluginNames();
  std::sort(plugins.begin(), plugins.end(),
            [pluginList](const QString& lhs, const QString& rhs) {
              return pluginList->priority(lhs) < pluginList->priority(rhs);
            });

  QStringList PrimaryPlugins = organizer()->managedGame()->primaryPlugins();
  QStringList DLCPlugins     = organizer()->managedGame()->DLCPlugins();
  QSet<QString> ManagedMods =
      QSet<QString>(PrimaryPlugins.begin(), PrimaryPlugins.end());
  QSet<QString> DLCSet = QSet<QString>(DLCPlugins.begin(), DLCPlugins.end());
  ManagedMods.subtract(DLCSet);
  PrimaryPlugins.append(QList<QString>(ManagedMods.begin(), ManagedMods.end()));

  // TODO: do not write plugins in OFFICIAL_FILES container
  for (const QString& pluginName : plugins) {
    if (!PrimaryPlugins.contains(pluginName, Qt::CaseInsensitive) &&
        !pluginList->isBlueprintFlagged(pluginName) &&
        !pluginName.startsWith(m_Organizer->managedGame()->blueprintPrefix(),
                               Qt::CaseInsensitive)) {
      if (pluginList->state(pluginName) == IPluginList::STATE_ACTIVE) {
        auto result = encoder.encode(pluginName);
        if (encoder.hasError()) {
          invalidFileNames = true;
          qCritical("invalid plugin name %s", qUtf8Printable(pluginName));
        } else {
          contents.append("*");
          contents.append(result);
        }
        contents.append("\r\n");
      } else {
        auto result = encoder.encode(pluginName);
        if (encoder.hasError()) {
          invalidFileNames = true;
          qCritical("invalid plugin name %s", qUtf8Printable(pluginName));
        } else {
          contents.append(result);
        }
        contents.append("\r\n");
      }
    }
  }

  if (invalidFileNames) {
    recordInvalidFileNames();
  }

  TransactionalWriteFile file(filePath);
  if (!file.replaceWith(contents)) {
    recordWriteFailure(filePath, file.errorString());
    return;
  }
}

QStringList StarfieldGamePlugins::readPluginList(MOBase::IPluginList* pluginList)
{
  if (m_Organizer->managedGame()->loadOrderMechanism() ==
      MOBase::IPluginGame::LoadOrderMechanism::PluginsTxt) {
    return CreationGamePlugins::readPluginList(pluginList);
  }
  return {};
}
