"""State-backed ``GamePlugins`` adapter for OpenMW.

Version-3 selection state is authoritative.  The Plugins tab, ``plugins.txt``,
and ``loadorder.txt`` are transactionally verified projections of that state.
"""

from __future__ import annotations

import copy
import os
import shutil
import stat
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

from PyQt6.QtCore import QTimer, qCritical, qDebug, qInfo, qWarning

import mobase

from .openmw_cfg import (
    canonical_plugin_name,
    migrate_selection_state,
    parse_openmw_selection_chain,
    project_plugin_lists,
    read_legacy_archive_file,
    read_legacy_plugin_file,
    read_morrowind_ini,
    read_selection_state,
    reconcile_plugin_inventory,
    rollback_file_changes,
    TransactionCleanupError,
    TransactionRollbackError,
    validate_file_roles,
    validate_selection_state,
    write_selection_state,
)

_STATE_FILE = "fluorine-openmw-selection.json"
_PROJECTION_HEADER = "# This file was automatically generated by Mod Organizer.\n"
_WRAPPER_SUFFIXES = (".omwaddon.esp", ".omwscripts.esp", ".omwgame.esp")


@dataclass(frozen=True)
class _ProfilePaths:
    directory: Path
    state: Path
    plugins: Path
    loadorder: Path
    groundcover: Path
    archives: Path
    morrowind_ini: Path
    openmw_cfg: Path


@dataclass(frozen=True)
class _UISnapshot:
    order: tuple[str, ...]
    active: tuple[tuple[str, bool], ...]


@dataclass(frozen=True)
class _WriteRequest:
    paths: _ProfilePaths
    plugin_list: object
    ui: _UISnapshot


@dataclass(frozen=True)
class _CommittedSnapshot:
    paths: _ProfilePaths
    ui: _UISnapshot
    state: dict
    revision: int


@dataclass
class _InventoryRefresh:
    diagnostics: dict | None = None
    implicit: bool = False


def _unique_names(*groups: Iterable[str]) -> list[str]:
    result: list[str] = []
    seen: set[str] = set()
    for group in groups:
        for name in group:
            folded = name.casefold()
            if name and folded not in seen:
                seen.add(folded)
                result.append(name)
    return result


def _replace_slots(
    complete: Sequence[str], available: Iterable[str], replacement: Sequence[str]
) -> list[str]:
    """Replace available slots while retaining unavailable entries in place."""
    available_keys = {name.casefold() for name in available}
    indexes = [
        index
        for index, name in enumerate(complete)
        if name.casefold() in available_keys
    ]
    if len(indexes) != len(replacement):
        raise ValueError("OpenMW available plugin slots do not match the UI")
    result = list(complete)
    for index, name in zip(indexes, replacement):
        result[index] = name
    return result


def _state_with_groundcover(state: dict, groundcover: Sequence[str]) -> dict:
    """Apply the documented non-empty groundcover classification input."""
    if not groundcover:
        return copy.deepcopy(state)
    candidate = copy.deepcopy(state)
    previous_groundcover = {
        name.casefold() for name in candidate["groundcover"]
    }
    order_keys = {name.casefold() for name in candidate["plugin_order"]}
    for name in groundcover:
        if name.casefold() not in order_keys:
            order_keys.add(name.casefold())
            candidate["plugin_order"].append(name)
    order_by_key = {
        name.casefold(): name for name in candidate["plugin_order"]
    }
    candidate["groundcover"] = [
        order_by_key[name.casefold()] for name in groundcover
    ]
    enabled = {name.casefold() for name in candidate["enabled_plugins"]}
    enabled.update(
        name.casefold()
        for name in candidate["groundcover"]
        if name.casefold() not in previous_groundcover
    )
    candidate["enabled_plugins"] = [
        name for name in candidate["plugin_order"]
        if name.casefold() in enabled
    ]
    validate_selection_state(candidate)
    return candidate


def _merge_ui_into_state(
    state: dict,
    ui: _UISnapshot,
    primary_plugins: Sequence[str],
) -> dict:
    """Merge available UI order/states into complete canonical state slots."""
    reconciled = reconcile_plugin_inventory(
        state, ui.order, primary_plugins
    )["state"]
    ui_by_key = {name.casefold(): name for name in ui.order}
    if len(ui_by_key) != len(ui.order):
        raise ValueError("The OpenMW Plugins tab contains duplicate identities")

    primary_by_key = {name.casefold(): name for name in primary_plugins}
    available_primary = [
        ui_by_key[name.casefold()]
        for name in primary_plugins
        if name.casefold() in ui_by_key
    ]
    ordered_ui = available_primary + [
        name for name in ui.order if name.casefold() not in primary_by_key
    ]
    candidate = copy.deepcopy(reconciled)
    candidate["plugin_order"] = _replace_slots(
        reconciled["plugin_order"], ui.order, ordered_ui
    )

    active = {
        name.casefold()
        for name in reconciled["enabled_plugins"]
        if name.casefold() not in ui_by_key
    }
    active.update(
        name.casefold()
        for name, enabled in ui.active
        if enabled
    )
    active.update(primary_by_key)
    candidate["enabled_plugins"] = [
        name for name in candidate["plugin_order"]
        if name.casefold() in active
    ]

    groundcover_keys = {
        name.casefold() for name in reconciled["groundcover"]
    }
    available_groundcover = [
        name for name in ordered_ui if name.casefold() in groundcover_keys
    ]
    candidate["groundcover"] = _replace_slots(
        reconciled["groundcover"],
        (
            name for name in reconciled["groundcover"]
            if name.casefold() in ui_by_key
        ),
        available_groundcover,
    )
    order_by_key = {
        name.casefold(): name for name in candidate["plugin_order"]
    }
    candidate["groundcover"] = [
        order_by_key[name.casefold()] for name in candidate["groundcover"]
    ]
    validate_selection_state(candidate)
    return candidate


def _atomic_write_text(path: Path, text: str) -> None:
    target = path.absolute().resolve(strict=False)
    fd, temporary = tempfile.mkstemp(
        prefix=f".{target.name}.", suffix=".tmp", dir=target.parent
    )
    temporary_path = Path(temporary)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        if target.exists():
            shutil.copymode(target, temporary_path)
        os.replace(temporary_path, target)
        try:
            directory = os.open(
                target.parent,
                os.O_RDONLY | getattr(os, "O_DIRECTORY", 0),
            )
            try:
                os.fsync(directory)
            finally:
                os.close(directory)
        except OSError:
            pass
    except BaseException:
        temporary_path.unlink(missing_ok=True)
        raise


def _projection_text(names: Sequence[str]) -> str:
    return _PROJECTION_HEADER + "".join(f"{name}\n" for name in names)


def _read_projection_exact(path: Path) -> list[str]:
    result: list[str] = []
    for line in path.read_text(encoding="utf-8", errors="strict").splitlines():
        if line.startswith("#"):
            continue
        if not line:
            continue
        if line != line.strip():
            raise ValueError(f"Noncanonical whitespace in {path}")
        result.append(line)
    return result


def _reconcile_archives(
    state: dict,
    available: Sequence[str],
    previously_known: Sequence[str] | None = None,
) -> dict:
    """Reconcile inventory without conflating known and selected order."""
    candidate = copy.deepcopy(state)
    providers = {name.casefold(): name for name in available}
    known_keys = {
        name.casefold()
        for name in (
            candidate["known_archives"]
            if previously_known is None
            else previously_known
        )
    }
    selected_keys = {name.casefold() for name in candidate["archives"]}
    newly_available = sorted(
        (name for key, name in providers.items() if key not in known_keys),
        key=lambda name: (name.casefold(), name),
    )
    candidate_known_keys = {
        name.casefold() for name in candidate["known_archives"]
    }
    new_archives = [
        name
        for name in newly_available
        if name.casefold() not in candidate_known_keys
    ]
    candidate["known_archives"] = [
        providers.get(name.casefold(), name)
        for name in candidate["known_archives"]
    ] + new_archives
    candidate["archives"] = [
        providers.get(name.casefold(), name)
        for name in candidate["archives"]
    ] + [
        name
        for name in newly_available
        if name.casefold() not in selected_keys
    ]
    validate_selection_state(candidate)
    return candidate


def _enable_new_plugins(
    state: dict, available: Sequence[str], previously_known: Sequence[str]
) -> dict:
    candidate = copy.deepcopy(state)
    known_keys = {
        canonical_plugin_name(name).casefold() for name in previously_known
    }
    available_keys = {
        canonical_plugin_name(name).casefold() for name in available
    }
    enabled_keys = {
        name.casefold() for name in candidate["enabled_plugins"]
    }
    enabled_keys.update(available_keys - known_keys)
    candidate["enabled_plugins"] = [
        name
        for name in candidate["plugin_order"]
        if name.casefold() in enabled_keys
    ]
    validate_selection_state(candidate)
    return candidate


class OpenMWGamePlugins(mobase.GamePlugins):
    def __init__(self, organizer: mobase.IOrganizer):
        super().__init__()
        self._organizer = organizer
        self._applying_ui = False
        self._writing = False
        self._write_scheduled = False
        self._pending: _WriteRequest | None = None
        self._sticky_error: BaseException | None = None
        self._fatal_error: BaseException | None = None
        self._committed: _CommittedSnapshot | None = None
        self._export_candidate: dict | None = None
        self._export_revision: int | None = None
        self._next_revision = 1
        self._logged_inventory_details: set[str] = set()
        self._inventory_refreshes: list[_InventoryRefresh] = []

    def _paths(self) -> _ProfilePaths:
        directory = Path(self._organizer.profile().absolutePath())
        return _ProfilePaths(
            directory=directory,
            state=directory / _STATE_FILE,
            plugins=directory / "plugins.txt",
            loadorder=directory / "loadorder.txt",
            groundcover=directory / "groundcover.txt",
            archives=directory / "archives.txt",
            morrowind_ini=directory / "Morrowind.ini",
            openmw_cfg=directory / "openmw.cfg",
        )

    def _primary_plugins(self) -> list[str]:
        return list(self._organizer.managedGame().primaryPlugins())

    def _selection_token_contexts(self) -> list[dict[str, Path]]:
        home = Path.home()
        native_cfg = Path(
            os.environ.get("XDG_CONFIG_HOME", str(home / ".config"))
        ) / "openmw"
        native_data = Path(
            os.environ.get("XDG_DATA_HOME", str(home / ".local/share"))
        ) / "openmw"
        contexts: list[dict[str, Path]] = []
        native_executable_dirs = {
            Path(executable).resolve().parent
            for name in ("openmw", "openmw-launcher")
            if (executable := shutil.which(name)) is not None
        }
        try:
            for configured in self._organizer.executablesList().executables():
                binary = Path(
                    configured.binaryInfo().absoluteFilePath()
                ).resolve()
                if binary.name.casefold() in ("openmw", "openmw-launcher"):
                    native_executable_dirs.add(binary.parent)
        except Exception:
            pass
        for executable_dir in sorted(native_executable_dirs):
            prefix = executable_dir.parent
            contexts.append(
                {
                    "?local?": executable_dir,
                    "?userconfig?": native_cfg,
                    "?userdata?": native_data,
                    "?global?": prefix / "share/games/openmw",
                }
            )
        if not native_executable_dirs and (native_cfg / "openmw.cfg").is_file():
            contexts.append(
                {
                    "?userconfig?": native_cfg,
                    "?userdata?": native_data,
                    "?global?": Path("/usr/share/games/openmw"),
                }
            )

        flatpak_home = home / ".var/app/org.openmw.OpenMW"
        deployment: Path | None = None
        flatpak = shutil.which("flatpak")
        if flatpak:
            try:
                result = subprocess.run(
                    [
                        flatpak,
                        "info",
                        "--show-location",
                        "org.openmw.OpenMW",
                    ],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.DEVNULL,
                    timeout=10,
                    check=False,
                )
                if result.returncode == 0:
                    location = Path(
                        result.stdout.decode("utf-8", "replace").strip()
                    )
                    if location.is_absolute():
                        deployment = location
            except Exception:
                pass
        if deployment is not None:
            context = {
                "?userconfig?": flatpak_home / "config/openmw",
                "?userdata?": flatpak_home / "data/openmw",
            }
            if deployment is not None:
                files = deployment / "files"
                context["?local?"] = files / "bin"
                context["?global?"] = files / "share/games/openmw"
            contexts.append(context)

        if not contexts:
            contexts.append(
                {
                    "?userconfig?": native_cfg,
                    "?userdata?": native_data,
                    "?global?": Path("/usr/share/games/openmw"),
                }
            )
        return contexts

    def _parse_profile_selection(self, cfg_path: Path) -> dict:
        selections: list[dict] = []
        try:
            local_settings = self._organizer.profile().localSettingsEnabled()
        except Exception:
            local_settings = True
        for context in self._selection_token_contexts():
            source = (
                cfg_path
                if local_settings
                else context["?userconfig?"] / "openmw.cfg"
            )
            selection = parse_openmw_selection_chain(source, context)
            if selection not in selections:
                selections.append(selection)
        if len(selections) != 1:
            raise ValueError(
                "OpenMW profile config path tokens resolve differently for the "
                "installed native and Flatpak engines"
            )
        return selections[0]

    def pathTokensForLaunch(
        self, flatpak: bool, executable_path: str
    ) -> dict[str, Path]:
        """Return the exact token roots for the selected launch environment."""
        home = Path.home()
        if not flatpak:
            executable = Path(executable_path).expanduser()
            if not executable.is_absolute():
                resolved = shutil.which(executable_path)
                if resolved is None:
                    raise RuntimeError(
                        "Could not resolve the selected native OpenMW executable"
                    )
                executable = Path(resolved)
            executable_dir = executable.resolve().parent
            prefix = executable_dir.parent
            return {
                "?local?": executable_dir,
                "?userconfig?": Path(
                    os.environ.get("XDG_CONFIG_HOME", str(home / ".config"))
                )
                / "openmw",
                "?userdata?": Path(
                    os.environ.get(
                        "XDG_DATA_HOME", str(home / ".local/share")
                    )
                )
                / "openmw",
                "?global?": prefix / "share/games/openmw",
            }
        expected_user_config = (
            home / ".var/app/org.openmw.OpenMW/config/openmw"
        ).resolve(strict=False)
        for context in self._selection_token_contexts():
            if context["?userconfig?"].resolve(strict=False) == expected_user_config:
                return context
        raise RuntimeError(
            "Could not resolve OpenMW path tokens for the Flatpak launch"
        )

    def _inventory_directories(self) -> list[Path]:
        """Return the ordered physical roots contributing inventory names."""
        directories: list[tuple[Path, bool, str]] = []
        try:
            game_dir = Path(
                self._organizer.managedGame().gameDirectory().absolutePath()
            )
            directories.append((game_dir / "Data Files", True, "game data"))
        except Exception as error:
            raise RuntimeError(
                f"Could not discover the OpenMW game data directory: {error}"
            ) from error

        try:
            mod_list = self._organizer.modList()
            mod_names = list(mod_list.allModsByProfilePriority())
        except Exception as error:
            raise RuntimeError(
                f"Could not enumerate the OpenMW mod inventory: {error}"
            ) from error

        for name in mod_names:
            if name == "Overwrite":
                continue
            try:
                if not (mod_list.state(name) & mobase.ModState.ACTIVE):
                    continue
                mod = mod_list.getMod(name)
                if mod is None:
                    raise RuntimeError("the organizer returned no mod handle")
                directories.append(
                    (Path(mod.absolutePath()), True, f"active mod {name!r}")
                )
            except Exception as error:
                raise RuntimeError(
                    f"Could not inspect OpenMW mod {name!r}: {error}"
                ) from error

        try:
            overwrite = mod_list.getMod("Overwrite")
            if overwrite is None:
                raise RuntimeError("the organizer returned no Overwrite handle")
            if overwrite is not None:
                directories.append(
                    (
                        Path(overwrite.absolutePath()),
                        True,
                        "Overwrite mod",
                    )
                )
        except Exception as error:
            raise RuntimeError(
                f"Could not inspect the OpenMW Overwrite mod: {error}"
            ) from error

        result: list[Path] = []
        seen: set[str] = set()
        for directory, required, label in directories:
            resolved = directory.resolve(strict=False)
            try:
                mode = resolved.stat().st_mode
            except FileNotFoundError as error:
                if required:
                    raise OSError(
                        f"Required OpenMW inventory root for {label} is missing: "
                        f"{resolved}"
                    ) from error
                continue
            except OSError as error:
                raise OSError(
                    f"Could not inspect OpenMW inventory root {resolved}: {error}"
                ) from error
            if not stat.S_ISDIR(mode):
                if required:
                    raise OSError(
                        f"Required OpenMW inventory root for {label} is not a "
                        f"directory: {resolved}"
                    )
                continue
            key = str(resolved)
            if key not in seen:
                seen.add(key)
                result.append(resolved)
        return result

    @staticmethod
    def _scan_inventory_directories(
        directories: Sequence[Path],
    ) -> tuple[list[str], list[str]]:
        """Enumerate wrapper-only aliases and physical archives."""

        wrappers: list[str] = []
        archives: list[str] = []
        seen_wrappers: set[str] = set()
        seen_archives: set[str] = set()
        for directory in directories:
            try:
                entries = sorted(directory.iterdir(), key=lambda path: path.name.casefold())
            except OSError as error:
                raise OSError(
                    f"Could not enumerate OpenMW inventory root {directory}: {error}"
                ) from error
            for entry in entries:
                try:
                    mode = entry.stat().st_mode
                except FileNotFoundError as error:
                    try:
                        is_broken_link = stat.S_ISLNK(entry.lstat().st_mode)
                    except OSError:
                        is_broken_link = False
                    if is_broken_link:
                        continue
                    raise OSError(
                        f"Could not inspect OpenMW inventory entry {entry}: {error}"
                    ) from error
                except OSError as error:
                    raise OSError(
                        f"Could not inspect OpenMW inventory entry {entry}: {error}"
                    ) from error
                if not stat.S_ISREG(mode):
                    continue
                folded = entry.name.casefold()
                if folded.endswith(_WRAPPER_SUFFIXES):
                    if folded not in seen_wrappers:
                        seen_wrappers.add(folded)
                        wrappers.append(entry.name)
                elif folded.endswith(".bsa") and folded not in seen_archives:
                    seen_archives.add(folded)
                    archives.append(entry.name)
        return wrappers, archives

    def _scan_profile_inventory(
        self, _paths: _ProfilePaths
    ) -> tuple[list[str], list[str]]:
        """Scan the complete physical inventory for the current profile."""
        directories = self._inventory_directories()
        return self._scan_inventory_directories(directories)

    @staticmethod
    def _is_missing(state: object) -> bool:
        missing = getattr(mobase.PluginState, "MISSING", None)
        return missing is not None and state == missing

    def _capture_ui(self, plugin_list: object) -> _UISnapshot:
        rows: list[tuple[int, int, str, object]] = []
        for index, name in enumerate(plugin_list.pluginNames()):
            state = plugin_list.state(name)
            if self._is_missing(state):
                continue
            rows.append((plugin_list.priority(name), index, str(name), state))
        rows.sort(key=lambda row: (row[0], row[1]))
        order = tuple(row[2] for row in rows)
        if len({name.casefold() for name in order}) != len(order):
            raise ValueError("The OpenMW Plugins tab contains duplicate identities")
        active_state = mobase.PluginState.ACTIVE
        return _UISnapshot(
            order,
            tuple((row[2], row[3] == active_state) for row in rows),
        )

    def _desired_ui(self, state: dict, available: Sequence[str]) -> _UISnapshot:
        result = reconcile_plugin_inventory(
            state, available, self._primary_plugins()
        )
        active = {name.casefold() for name in result["state"]["enabled_plugins"]}
        return _UISnapshot(
            tuple(result["available_plugins"]),
            tuple(
                (name, name.casefold() in active)
                for name in result["available_plugins"]
            ),
        )

    def _apply_ui(self, plugin_list: object, snapshot: _UISnapshot) -> None:
        inactive = mobase.PluginState.INACTIVE
        active = mobase.PluginState.ACTIVE
        self._applying_ui = True
        try:
            plugin_list.setLoadOrder(list(snapshot.order))
            for name, enabled in snapshot.active:
                plugin_list.setState(name, active if enabled else inactive)
        finally:
            self._applying_ui = False

    def _verify_ui(self, plugin_list: object, expected: _UISnapshot) -> None:
        actual = self._capture_ui(plugin_list)
        if actual != expected:
            raise RuntimeError(
                "The OpenMW Plugins tab did not accept the exact canonical state"
            )

    def _restore_ui(self, plugin_list: object, snapshot: _UISnapshot) -> None:
        try:
            self._apply_ui(plugin_list, snapshot)
            self._verify_ui(plugin_list, snapshot)
        except BaseException as error:
            raise RuntimeError(
                f"OpenMW Plugins tab rollback failed: {error}"
            ) from error

    def _load_candidate(
        self,
        paths: _ProfilePaths,
        available: Sequence[str],
        *,
        scan_inventory: bool = True,
    ) -> tuple[dict, dict]:
        state = read_selection_state(paths.state)
        legacy_groundcover = read_legacy_plugin_file(paths.groundcover)
        if scan_inventory:
            wrapper_aliases, physical_archives = self._scan_profile_inventory(paths)
        else:
            wrapper_aliases, physical_archives = [], []
        inventory = [*available, *wrapper_aliases]
        if isinstance(state, dict) and state.get("version") == 3:
            candidate = migrate_selection_state(
                state,
                available_plugins=inventory,
                available_archives=_unique_names(
                    state["known_archives"], state["archives"]
                ),
                primary_plugins=self._primary_plugins(),
            )
            candidate = _state_with_groundcover(
                candidate, legacy_groundcover
            )
            candidate = _reconcile_archives(candidate, physical_archives)
            result = reconcile_plugin_inventory(
                candidate, inventory, self._primary_plugins()
            )
            return result["state"], result

        ini = read_morrowind_ini(paths.morrowind_ini)
        configured = self._parse_profile_selection(paths.openmw_cfg)
        legacy_plugins = read_legacy_plugin_file(paths.plugins)
        legacy_loadorder = read_legacy_plugin_file(paths.loadorder)
        legacy_archives = read_legacy_archive_file(paths.archives)

        state_archives = (
            _unique_names(
                state.get("known_archives", []), state.get("archives", [])
            )
            if isinstance(state, dict) else []
        )
        if isinstance(state, dict):
            available_archives = state_archives
        elif configured["fallback_archive_present"]:
            available_archives = _unique_names(
                physical_archives, configured["fallback_archive"]
            )
        else:
            available_archives = _unique_names(
                physical_archives, legacy_archives, ini["archives"]
            )
        candidate = migrate_selection_state(
            state,
            available_plugins=inventory,
            available_archives=available_archives,
            primary_plugins=self._primary_plugins(),
            morrowind_ini=ini,
            openmw_selection=configured,
            legacy_plugins=legacy_plugins,
            legacy_loadorder=legacy_loadorder,
            legacy_groundcover=legacy_groundcover,
            legacy_archives=legacy_archives,
        )
        if isinstance(state, dict):
            candidate = _enable_new_plugins(
                candidate, inventory, state.get("known_plugins", [])
            )
        if isinstance(state, dict):
            candidate = _reconcile_archives(
                candidate, physical_archives, state_archives
            )
        result = reconcile_plugin_inventory(
            candidate, inventory, self._primary_plugins()
        )
        return result["state"], result

    def _log_inventory_diagnostics(self, result: dict) -> None:
        ignored = result["ignored_alias_diagnostics"]
        wrapper_only = result["wrapper_only_alias_diagnostics"]
        details = zip(
            (
                *result["ignored_alias_identities"],
                *result["wrapper_only_alias_identities"],
            ),
            (*ignored, *wrapper_only),
            strict=True,
        )
        for identity, diagnostic in details:
            if identity not in self._logged_inventory_details:
                self._logged_inventory_details.add(identity)
                qDebug(f"OpenMW plugin inventory: {diagnostic}")

        if ignored and not wrapper_only:
            counts = result["ignored_alias_counts"]
            breakdown = ", ".join(
                f"{count} {kind}" for kind, count in counts.items()
            )
            noun = "alias" if len(ignored) == 1 else "aliases"
            qInfo(
                f"OpenMW plugin inventory: ignored {len(ignored)} legacy "
                f"{noun} ({breakdown})"
            )

        elif wrapper_only and not ignored:
            counts = result["wrapper_only_alias_counts"]
            breakdown = ", ".join(
                f"{count} {kind}" for kind, count in counts.items()
            )
            noun = "alias" if len(wrapper_only) == 1 else "aliases"
            qInfo(
                f"OpenMW plugin inventory: found {len(wrapper_only)} "
                f"wrapper-only legacy {noun} ({breakdown}); install the "
                "native plugin or remove the obsolete wrapper"
            )
        elif ignored and wrapper_only:
            counts: dict[str, int] = {}
            for source in (
                result["ignored_alias_counts"],
                result["wrapper_only_alias_counts"],
            ):
                for kind, count in source.items():
                    counts[kind] = counts.get(kind, 0) + count
            breakdown = ", ".join(
                f"{count} {kind}" for kind, count in sorted(counts.items())
            )
            total = len(ignored) + len(wrapper_only)
            noun = "alias" if total == 1 else "aliases"
            qInfo(
                f"OpenMW plugin inventory: processed {total} legacy {noun} "
                f"({breakdown}; ignored {len(ignored)}, wrapper-only "
                f"{len(wrapper_only)}); install native plugins or remove "
                "obsolete wrappers"
            )
        else:
            qInfo("OpenMW plugin inventory: ignored 0 legacy aliases")

        for diagnostic in result["duplicate_diagnostics"]:
            qWarning(f"OpenMW plugin inventory: {diagnostic}")

    def pluginListRefreshStarted(self) -> None:
        self._inventory_refreshes.append(_InventoryRefresh())

    def pluginListRefreshCompleted(self) -> None:
        if not self._inventory_refreshes:
            raise RuntimeError(
                "OpenMW plugin refresh completed without a matching start"
            )
        refresh = self._inventory_refreshes.pop()
        if refresh.diagnostics is not None:
            self._log_inventory_diagnostics(refresh.diagnostics)

    def pluginListRefreshFailed(self) -> None:
        if not self._inventory_refreshes:
            raise RuntimeError(
                "OpenMW plugin refresh failed without a matching start"
            )
        self._inventory_refreshes.pop()

    def _verify_files(
        self,
        paths: _ProfilePaths,
        state: dict,
        active_projection: Sequence[str],
        order_projection: Sequence[str],
    ) -> None:
        persisted = read_selection_state(paths.state)
        if persisted != state:
            raise RuntimeError("OpenMW selection state read-back differs from write")
        validate_selection_state(persisted)

        exact_plugins = _read_projection_exact(paths.plugins)
        exact_order = _read_projection_exact(paths.loadorder)
        parsed_plugins = read_legacy_plugin_file(paths.plugins)
        parsed_order = read_legacy_plugin_file(paths.loadorder)
        if exact_plugins != list(active_projection) or parsed_plugins != list(
            active_projection
        ):
            raise RuntimeError("OpenMW plugins.txt read-back differs from projection")
        if exact_order != list(order_projection) or parsed_order != list(
            order_projection
        ):
            raise RuntimeError("OpenMW loadorder.txt read-back differs from projection")

    def _persist_and_apply(
        self,
        paths: _ProfilePaths,
        state: dict,
        plugin_list: object,
        available: Sequence[str],
        *,
        apply_ui: bool = True,
    ) -> _UISnapshot:
        validate_selection_state(state)
        active_projection, order_projection = project_plugin_lists(
            state, available, self._primary_plugins()
        )
        if order_projection != state["plugin_order"]:
            raise RuntimeError("OpenMW state was not fully reconciled before writing")
        expected_ui = self._desired_ui(state, available)
        roles = {
            "selection state": paths.state,
            "active plugin projection": paths.plugins,
            "plugin order projection": paths.loadorder,
        }
        validate_file_roles(roles)
        try:
            with rollback_file_changes(roles.values()):
                write_selection_state(paths.state, state)
                _atomic_write_text(paths.plugins, _projection_text(active_projection))
                _atomic_write_text(paths.loadorder, _projection_text(order_projection))
                self._verify_files(
                    paths, state, active_projection, order_projection
                )
                if apply_ui:
                    self._apply_ui(plugin_list, expected_ui)
                    self._verify_ui(plugin_list, expected_ui)
        except TransactionCleanupError as error:
            self._install_commit(paths, expected_ui, state)
            self._fatal_error = error
            qCritical(str(error))
            raise
        return expected_ui

    def _install_commit(
        self, paths: _ProfilePaths, ui: _UISnapshot, state: dict
    ) -> None:
        self._committed = _CommittedSnapshot(
            paths, ui, copy.deepcopy(state), self._next_revision
        )
        self._next_revision += 1

    def _restore_committed(self, plugin_list: object) -> None:
        if self._committed is not None:
            self._restore_ui(plugin_list, self._committed.ui)

    def _execute_request(
        self, request: _WriteRequest, *, apply_ui: bool = True
    ) -> None:
        committed = self._committed
        if committed is None or committed.paths.directory.resolve(
            strict=False
        ) != request.paths.directory.resolve(strict=False):
            raise RuntimeError(
                "OpenMW plugin state has not been successfully hydrated for this profile"
            )
        candidate = _merge_ui_into_state(
            committed.state, request.ui, self._primary_plugins()
        )
        expected_ui = self._persist_and_apply(
            request.paths,
            candidate,
            request.plugin_list,
            request.ui.order,
            apply_ui=apply_ui,
        )
        self._install_commit(request.paths, expected_ui, candidate)

    def _remember_failure(
        self, plugin_list: object, error: BaseException, *, delayed: bool
    ) -> None:
        self._sticky_error = error
        if isinstance(error, (TransactionCleanupError, TransactionRollbackError)):
            self._fatal_error = error
            qCritical(str(error))
            return
        try:
            self._restore_committed(plugin_list)
        except BaseException as rollback_error:
            self._fatal_error = rollback_error
            qCritical(f"OpenMW plugin state rollback failed: {rollback_error}")
        if delayed:
            qCritical(f"OpenMW delayed plugin persistence failed: {error}")

    def _schedule_pending(self) -> None:
        if self._write_scheduled or self._pending is None:
            return
        self._write_scheduled = True
        QTimer.singleShot(0, self._run_delayed_write)

    def _run_delayed_write(self) -> None:
        if not self._write_scheduled:
            return
        self._write_scheduled = False
        if self._writing:
            self._schedule_pending()
            return
        if self._pending is None:
            return
        request = self._pending
        self._pending = None
        self._writing = True
        try:
            self._execute_request(request)
        except BaseException as error:
            self._remember_failure(request.plugin_list, error, delayed=True)
        else:
            self._sticky_error = None
        finally:
            self._writing = False
        if self._pending is not None:
            self._schedule_pending()

    def writePluginLists(self, plugin_list: mobase.IPluginList) -> None:
        if self._applying_ui:
            return
        if self._fatal_error is not None:
            qCritical(
                "OpenMW plugin persistence is blocked after an unrecoverable "
                f"failure: {self._fatal_error}"
            )
            return
        try:
            request = _WriteRequest(
                self._paths(), plugin_list, self._capture_ui(plugin_list)
            )
            self._pending = request
            self._schedule_pending()
        except BaseException as error:
            self._sticky_error = error
            qCritical(f"OpenMW could not queue plugin persistence: {error}")

    def blockPersistence(self, error: BaseException) -> None:
        """Permanently block this session after an incomplete launch rollback."""
        self._fatal_error = error
        qCritical(f"OpenMW plugin persistence is blocked: {error}")

    def flushPendingWrites(self, plugin_list: mobase.IPluginList) -> None:
        """Synchronously persist the latest UI state or raise the sticky error."""
        if self._fatal_error is not None:
            raise RuntimeError(
                "OpenMW plugin persistence is blocked after an unrecoverable "
                f"failure: {self._fatal_error}"
            ) from self._fatal_error
        if self._writing:
            raise RuntimeError("OpenMW plugin persistence is already in progress")
        paths = self._paths()
        current = self._capture_ui(plugin_list)
        committed = self._committed
        if (
            self._sticky_error is not None
            and self._pending is None
            and committed is not None
            and committed.paths.directory.resolve(strict=False)
            == paths.directory.resolve(strict=False)
            and committed.ui == current
        ):
            raise RuntimeError(
                f"Previous OpenMW plugin persistence failed: {self._sticky_error}"
            ) from self._sticky_error
        needs_write = (
            self._pending is not None
            or self._sticky_error is not None
            or committed is None
            or committed.paths.directory.resolve(strict=False)
            != paths.directory.resolve(strict=False)
            or committed.ui != current
        )
        if not needs_write:
            return
        request = _WriteRequest(paths, plugin_list, current)
        self._pending = None
        self._write_scheduled = False
        self._writing = True
        try:
            self._execute_request(request)
        except BaseException as error:
            self._remember_failure(plugin_list, error, delayed=False)
            raise self._sticky_error
        else:
            self._sticky_error = None
        finally:
            self._writing = False

    def readPluginLists(self, plugin_list: mobase.IPluginList) -> None:
        if self._fatal_error is not None:
            raise RuntimeError(
                "OpenMW plugin persistence is blocked after an unrecoverable "
                f"failure: {self._fatal_error}"
            ) from self._fatal_error
        if self._writing:
            raise RuntimeError("OpenMW plugin persistence is already in progress")
        if self._pending is not None:
            pending = self._pending
            self._pending = None
            self._write_scheduled = False
            self._writing = True
            try:
                # The directory refresher may already expose the next profile's
                # rows. Persist the captured old snapshot without applying it;
                # hydration below will apply the current profile exactly once.
                self._execute_request(pending, apply_ui=False)
            except BaseException as error:
                if isinstance(error, TransactionRollbackError):
                    self._fatal_error = error
                    qCritical(
                        "OpenMW old-profile persistence rollback was incomplete: "
                        f"{error}"
                    )
                else:
                    self._sticky_error = error
                raise
            finally:
                self._writing = False
        elif self._sticky_error is not None:
            raise RuntimeError(
                f"Previous OpenMW plugin persistence failed: {self._sticky_error}"
            ) from self._sticky_error

        if not self._inventory_refreshes:
            self._inventory_refreshes.append(_InventoryRefresh(implicit=True))
        elif self._inventory_refreshes[-1].implicit:
            self._inventory_refreshes[-1] = _InventoryRefresh(implicit=True)
        refresh = self._inventory_refreshes[-1]
        refresh.diagnostics = None
        paths = self._paths()
        before = self._capture_ui(plugin_list)
        candidate, inventory_diagnostics = self._load_candidate(
            paths, before.order
        )
        try:
            expected_ui = self._persist_and_apply(
                paths, candidate, plugin_list, before.order
            )
        except (TransactionCleanupError, TransactionRollbackError) as error:
            self._fatal_error = error
            raise
        except BaseException:
            try:
                self._restore_ui(plugin_list, before)
            except BaseException as rollback_error:
                self._fatal_error = rollback_error
                qCritical(f"OpenMW plugin state rollback failed: {rollback_error}")
                raise
            raise
        self._install_commit(paths, expected_ui, candidate)
        refresh.diagnostics = inventory_diagnostics
        self._sticky_error = None

    def getLoadOrder(self) -> Sequence[str]:
        """Read the best canonical order without mutating files, state, or UI."""
        paths = self._paths()
        state = read_selection_state(paths.state)
        if isinstance(state, dict) and state.get("version") == 3:
            validate_selection_state(state)
            return list(state["plugin_order"])
        candidate, _ = self._load_candidate(
            paths, (), scan_inventory=False
        )
        return list(candidate["plugin_order"])

    def lootSortSnapshot(self, plugin_list: mobase.IPluginList) -> dict:
        """Return a complete immutable-order snapshot for the LOOT tool."""
        self.flushPendingWrites(plugin_list)
        committed = self._committed
        if committed is None:
            raise RuntimeError("OpenMW plugin state is not initialized")
        available = {name.casefold() for name in committed.ui.order}
        active = {
            name.casefold() for name in committed.state["enabled_plugins"]
        }
        primary = {name.casefold() for name in self._primary_plugins()}
        groundcover = {
            name.casefold() for name in committed.state["groundcover"]
        }
        return {
            "revision": committed.revision,
            "rows": tuple(
                {
                    "name": name,
                    "active": name.casefold() in active,
                    "available": name.casefold() in available,
                    "primary": name.casefold() in primary,
                    "groundcover": name.casefold() in groundcover,
                }
                for name in committed.state["plugin_order"]
            ),
        }

    def exportSnapshot(self, plugin_list: mobase.IPluginList) -> dict:
        """Flush UI edits and prepare classification changes for launch."""
        self.flushPendingWrites(plugin_list)
        committed = self._committed
        if committed is None:
            raise RuntimeError("OpenMW plugin state is not initialized")

        candidate = copy.deepcopy(committed.state)
        groundcover = read_legacy_plugin_file(committed.paths.groundcover)
        if groundcover:
            candidate = _state_with_groundcover(candidate, groundcover)
            candidate = reconcile_plugin_inventory(
                candidate, committed.ui.order, self._primary_plugins()
            )["state"]
        self._export_candidate = copy.deepcopy(candidate)
        self._export_revision = committed.revision
        return {
            "state": copy.deepcopy(candidate),
            "available_plugins": list(committed.ui.order),
            "revision": committed.revision,
        }

    @staticmethod
    def _export_authority_matches(left: dict, right: dict) -> bool:
        fields = (
            "plugin_order",
            "enabled_plugins",
            "groundcover",
            "known_archives",
            "archives",
            "content_migration_source",
            "groundcover_migration_source",
            "archive_migration_source",
            "order_migration_source",
            "plugin_state_migrated",
        )
        return all(left[field] == right[field] for field in fields)

    def stageExportState(
        self, plugin_list: mobase.IPluginList, state: dict
    ) -> None:
        """Write and apply launch state inside the caller's rollback scope."""
        validate_selection_state(state)
        committed = self._committed
        candidate = self._export_candidate
        if (
            committed is None
            or candidate is None
            or committed.revision != self._export_revision
            or not self._export_authority_matches(state, candidate)
        ):
            raise RuntimeError("OpenMW launch state changed during export")
        expected_ui = self._desired_ui(state, committed.ui.order)
        active_projection, order_projection = project_plugin_lists(
            state, committed.ui.order, self._primary_plugins()
        )
        write_selection_state(committed.paths.state, state)
        _atomic_write_text(
            committed.paths.plugins, _projection_text(active_projection)
        )
        _atomic_write_text(
            committed.paths.loadorder, _projection_text(order_projection)
        )
        self._verify_files(
            committed.paths, state, active_projection, order_projection
        )
        try:
            self._apply_ui(plugin_list, expected_ui)
            self._verify_ui(plugin_list, expected_ui)
        except BaseException as original:
            try:
                self._restore_ui(plugin_list, committed.ui)
            except BaseException as rollback_error:
                self._fatal_error = rollback_error
                qCritical(
                    "OpenMW staged export UI rollback failed: "
                    f"{rollback_error}"
                )
                raise rollback_error from original
            raise

    def verifyExportState(
        self, plugin_list: mobase.IPluginList, state: dict
    ) -> None:
        """Verify selector-only launch updates before its rollback scope exits."""
        validate_selection_state(state)
        committed = self._committed
        if committed is None:
            raise RuntimeError("OpenMW plugin state is not initialized")

        candidate = self._export_candidate
        if (
            candidate is None
            or committed.revision != self._export_revision
            or not self._export_authority_matches(state, candidate)
        ):
            raise RuntimeError(
                "OpenMW launch export attempted to change canonical plugin state"
            )

        active_projection, order_projection = project_plugin_lists(
            state, committed.ui.order, self._primary_plugins()
        )
        self._verify_files(
            committed.paths, state, active_projection, order_projection
        )
        self._verify_ui(
            plugin_list, self._desired_ui(state, committed.ui.order)
        )

    def commitExportState(
        self, plugin_list: mobase.IPluginList, state: dict
    ) -> None:
        """Install selector-only state after launch transaction commit."""
        self.verifyExportState(plugin_list, state)
        committed = self._committed
        if committed is None:
            raise RuntimeError("OpenMW plugin state is not initialized")
        expected_ui = self._desired_ui(state, committed.ui.order)
        self._install_commit(committed.paths, expected_ui, state)
        self._export_candidate = None
        self._export_revision = None
        self._sticky_error = None

    def applyLootOrder(
        self,
        plugin_list: mobase.IPluginList,
        revision: object,
        complete_order: Sequence[str],
    ) -> bool:
        """Validate and transactionally install LOOT's complete merged order."""
        self.flushPendingWrites(plugin_list)
        committed = self._committed
        if committed is None or revision != committed.revision:
            raise RuntimeError(
                "OpenMW plugin state changed while LOOT was sorting; retry the sort"
            )
        old_order = committed.state["plugin_order"]
        if len(complete_order) != len(old_order):
            raise ValueError("LOOT returned an incomplete OpenMW plugin order")
        old_by_key = {name.casefold(): name for name in old_order}
        requested_keys = [str(name).casefold() for name in complete_order]
        if len(set(requested_keys)) != len(requested_keys) or set(
            requested_keys
        ) != set(old_by_key):
            raise ValueError("LOOT order is not a bijection of canonical state")
        canonical_order = [old_by_key[key] for key in requested_keys]

        available = {name.casefold() for name in committed.ui.order}
        active = {
            name.casefold() for name in committed.state["enabled_plugins"]
        }
        primary = {name.casefold() for name in self._primary_plugins()}
        groundcover = {
            name.casefold() for name in committed.state["groundcover"]
        }
        for index, old_name in enumerate(old_order):
            key = old_name.casefold()
            fixed = (
                key not in available
                or key not in active
                or key in primary
                or key in groundcover
                or key.endswith(".omwscripts")
            )
            if fixed and canonical_order[index].casefold() != key:
                raise ValueError(
                    f"LOOT attempted to move fixed OpenMW slot {old_name!r}"
                )

        candidate = copy.deepcopy(committed.state)
        candidate["plugin_order"] = canonical_order
        candidate["enabled_plugins"] = [
            name for name in canonical_order if name.casefold() in active
        ]
        candidate["groundcover"] = [
            name for name in canonical_order if name.casefold() in groundcover
        ]
        validate_selection_state(candidate)
        try:
            expected_ui = self._persist_and_apply(
                committed.paths,
                candidate,
                plugin_list,
                committed.ui.order,
            )
        except BaseException as error:
            self._remember_failure(plugin_list, error, delayed=False)
            raise self._sticky_error
        self._install_commit(committed.paths, expected_ui, candidate)
        self._sticky_error = None
        return True

    def lightPluginsAreSupported(self) -> bool:
        return False

    def mediumPluginsAreSupported(self) -> bool:
        return False

    def blueprintPluginsAreSupported(self) -> bool:
        return False


class OpenMWPluginListLifecycle(mobase.PluginListLifecycle):
    """Forward core refresh boundaries to the OpenMW state adapter."""

    def __init__(self, game_plugins: OpenMWGamePlugins):
        super().__init__()
        self._game_plugins = game_plugins

    def refreshStarted(self) -> None:
        self._game_plugins.pluginListRefreshStarted()

    def refreshCompleted(self) -> None:
        self._game_plugins.pluginListRefreshCompleted()

    def refreshFailed(self) -> None:
        self._game_plugins.pluginListRefreshFailed()

    def flushPendingWrites(self, plugin_list: mobase.IPluginList) -> None:
        self._game_plugins.flushPendingWrites(plugin_list)
